### ISSUE TITLE
ValueError: Invalid IPv6 URL in sanitize_token

### ISSUE THREAD

**Issue by papachoco** [html5lib/html5lib-python#195]
I get an exception at 

html5lib-0.999999-py2.7.egg/html5lib/sanitizer.py", line 210, in allowed_token

uri = urlparse.urlparse(val_unescaped)

when I passed the following malformed expression

`exp = u'<html><a href=\'http://tag:nextthought.com,2011-10:julie.zhu-OID-0x148a37:55736572735f315f54657374:hjJe3dfZMVb,"body":["5:::{\\"args\\\'>foo</html>'`

I guess if it's a malformed url we should ignore it ?

Thanks a lot

Carlos

**Comment by gsnedders** [comment]
Le sigh. There's nothing about it throwing ever in the docs… The attribute should probably just be dropped, given we can't check it if we can't parse it.

**Comment by alex** [comment]
FWIW, here's a slightly more minified test case:

```pytb
>>>> html5lib.HTMLParser(tokenizer=html5lib.sanitizer.HTMLSanitizer).parseFragment(u'<a href="h://]">')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/html5parser.py", line 253, in parseFragment
    self._parse(stream, True, container=container, encoding=encoding)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/html5parser.py", line 94, in _parse
    self.mainLoop()
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/html5parser.py", line 166, in mainLoop
    for token in self.normalizedTokens():
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/html5parser.py", line 222, in normalizedTokens
    for token in self.tokenizer:
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/sanitizer.py", line 294, in __iter__
    token = self.sanitize_token(token)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/sanitizer.py", line 190, in sanitize_token
    return self.allowed_token(token, token_type)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-2c243013021c3/site-packages/html5lib/sanitizer.py", line 210, in allowed_token
    uri = urlparse.urlparse(val_unescaped)
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.1/lib-python/2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/Users/alex_gaynor/.pyenv/versions/pypy-2.6.1/lib-python/2.7/urlparse.py", line 214, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by dstufft** [comment]
What's the best way of getting this sorted? We're hitting this error a good amount of the time on PyPI.

**Comment by gsnedders** [comment]
Um. I'm sure I fixed this somewhere. Weird. As I said on IRC, you just want a try/catch around the parsing, and drop the attribute if urlparse can't parse it (i.e., assume it's bad). If you throw up a PR for that I'll merge it tomorrow and push a release. And add a test for it similar to `test_invalid_data_uri`.

**Comment by alex** [comment]
yay, thanks!

**Comment by gsnedders** [comment]
0.9999999 has now been released with this fixed. (And the identical 1.0b8, for historical reasons.)
