### ISSUE TITLE
AttributeError: 'TreeWalker' object has no attribute 'fragmentChildren'

### ISSUE THREAD

**Issue by paradoxxxzero** [html5lib/html5lib-python#228]
For some reason my `tree` (`lxml.etree._Element`) object has no attribute getroot and is not a list so there is no `fragmentChildren` attribute on `TreeWalker`: 270a2ca14fafc989f8f1bd4f79db2f4bd9f4d1fc

lxml 3.5.0
html5lib-python f796cca5f9ddaaf1e1a8b872f68455551cd3ae2d

**Comment by gsnedders** [comment]
Where does your tree object come from? (We should probably add an `assert False, "unreachable"` there.)

**Comment by paradoxxxzero** [comment]
I narrowed down the problem to:
```python
from lxml.html import fromstring
from html5lib import treewalkers, serializer


lxmltree = fromstring('<div><div><div></div></div></div>')
walker = treewalkers.getTreeWalker('lxml')
stream = walker(lxmltree)
s = serializer.htmlserializer.HTMLSerializer()
output = s.render(stream)
```

Which gives:

```python
Traceback (most recent call last):
  File "html5fail.py", line 9, in <module>
    output = s.render(stream)
  File "<path>/html5lib-python/html5lib/serializer/htmlserializer.py", line 306, in render
    return "".join(list(self.serialize(treewalker)))
  File "<path>/html5lib-python/html5lib/serializer/htmlserializer.py", line 196, in serialize
    for token in treewalker:
  File "<path>/html5lib-python/html5lib/filters/optionaltags.py", line 17, in __iter__
    for previous, token, next in self.slider():
  File "<path>/html5lib-python/html5lib/filters/optionaltags.py", line 9, in slider
    for token in self.source:
  File "<path>/html5lib-python/html5lib/treewalkers/_base.py", line 150, in __iter__
    currentNode = self.getParentNode(currentNode)
  File "<path>/html5lib-python/html5lib/treewalkers/lxmletree.py", line 202, in getParentNode
    elif node in self.fragmentChildren:
AttributeError: 'TreeWalker' object has no attribute 'fragmentChildren'
```

Python 3.5.1
