### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'element'

### ISSUE THREAD

**Issue by guettli** [html5lib/html5lib-python#232]
I get this exception

```
Error
Traceback (most recent call last):
  File "/home/h/src/dt/dt/tests/unit/utils/test_convertutils.py", line 74, in test_html_to_html__with_html_which_produces_attribute_error_in_html5lib
    html=convertutils.html_to_html(html)
  File "/home/h/src/dt/dt/utils/convertutils.py", line 33, in html_to_html
    soup = bs4.BeautifulSoup(html, 'html5lib') # https://tbz-work.tbz-pariv.lan/foo_tbz_p/beleg/71588/
  File "/home/h/lib/python2.7/site-packages/bs4/__init__.py", line 196, in __init__
    self._feed()
  File "/home/h/lib/python2.7/site-packages/bs4/__init__.py", line 210, in _feed
    self.builder.feed(self.markup)
  File "/home/h/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 37, in feed
    doc = parser.parse(markup, encoding=self.user_specified_encoding)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 236, in parse
    parseMeta=parseMeta, useChardet=useChardet)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 94, in _parse
    self.mainLoop()
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 201, in mainLoop
    new_token = phase.processEndTag(new_token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 493, in processEndTag
    return self.endTagHandler[token["name"]](token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 2049, in endTagOther
    return self.parser.phases["inTable"].processEndTag(token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 493, in processEndTag
    return self.endTagHandler[token["name"]](token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 1769, in endTagOther
    self.parser.phases["inBody"].processEndTag(token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 493, in processEndTag
    return self.endTagHandler[token["name"]](token)
  File "/home/h/src/html5lib/html5lib/html5parser.py", line 1539, in endTagFormatting
    parent.insertBefore(lastNode, insertBefore)
  File "/home/h/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 205, in insertBefore
    index = self.element.index(refNode.element)
AttributeError: 'NoneType' object has no attribute 'element'
```
If I do this:

```
        html=open('/tmp/html_which_produces_attribute_error_in_html5lib.html').read().decode('utf8')
        soup = bs4.BeautifulSoup(html, 'html5lib')
```

You can get the html file from this gist: https://gist.github.com/guettli/4d2541a9b2bc3671c4332ff4e89ca2eb

Up to now I use this work-around:
```
    try:
        soup = bs4.BeautifulSoup(html, 'html5lib')
    except AttributeError:
        soup = bs4.BeautifulSoup(html, 'lxml')
```

Version: current master of html5lib.

**Comment by gsnedders** [comment]
I suspect this is a bug in BS4, FWIW. I'm aware BS4's html5lib tree builder has bugs. You could try seeing if <https://code.launchpad.net/~geoffers/beautifulsoup/html5lib-tests/+merge/279911> fixes it.

**Comment by gsnedders** [comment]
That HTML file reduces down to `<table><FONT><P></FONT>` while still causing that exception be thrown, which is fixed in the aforementioned merge request on BS4. Closing this as a BS4 bug.

**Comment by gsnedders** [comment]
Specifically, http://bazaar.launchpad.net/~geoffers/beautifulsoup/html5lib-tests/revision/399 is the commit which fixes this.

**Comment by TZanke** [comment]
This branch is now merged into master:
https://code.launchpad.net/~geoffers/beautifulsoup/html5lib-tests/+merge/279911

Lets give it a try.
