### ISSUE TITLE
-- In comment breaks parsing with treebuilder="lxml"

### ISSUE THREAD

**Issue by jelly** [html5lib/html5lib-python#236]
To reproduce:

```
>>> html5lib.parse('<!-- -- -->', treebuilder="lxml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 29, in parse
    return p.parse(doc, encoding=encoding)
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 236, in parse
    parseMeta=parseMeta, useChardet=useChardet)
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 94, in _parse
    self.mainLoop()
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 217, in mainLoop
    reprocess = self.phase.processEOF()
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 632, in processEOF
    self.insertHtmlElement()
  File "/usr/lib/python2.7/site-packages/html5lib/html5parser.py", line 627, in insertHtmlElement
    self.tree.insertRoot(impliedTagToken("html", "StartTag"))
  File "/usr/lib/python2.7/site-packages/html5lib/treebuilders/etree_lxml.py", line 347, in insertRoot
    root.addprevious(etree.Comment(comment_token["data"]))
  File "src/lxml/lxml.etree.pyx", line 3017, in lxml.etree.Comment (src/lxml/lxml.etree.c:75666)
ValueError: Comment may not contain '--' or end with '-'
```

A performance degrading solution is here https://github.com/kovidgoyal/calibre/commit/c68b9b7d64ab08ae78bf461b0e4683ce54222aa2

**Comment by jelly** [comment]
Nevermind this has already been fixed in git. Is there a new release soon?

**Comment by gsnedders** [comment]
@jelly Soon(ish). I was trying to sort out the mess caused by backwards incompatible setuptools changes and try and release something compatible with both old and new setuptools, rather than break plenty of people's systems…

**Comment by gsnedders** [comment]
https://github.com/html5lib/html5lib-python/commit/0c551c9519e47f76f8f185089ed71cb9539b6e00 is the upstream fix, FWIW.
