### ISSUE TITLE
Import error on macos

### ISSUE THREAD

**Issue by nomadyow** [html5lib/html5lib-python#305]
If I do:

Import html5lib

on my mac  (python 2.7)

I get the following:

`Traceback (most recent call last):
  File "./test2.py", line 2, in <module>
    import html5lib
  File "build/bdist.macosx-10.12-intel/egg/html5lib/__init__.py", line 16, in <module>
  File "build/bdist.macosx-10.12-intel/egg/html5lib/html5parser.py", line 2, in <module>
ImportError: cannot import name viewkeys`

**Comment by gsnedders** [comment]
That's an out-of-date `six`, if you update `six` it should work; see also #301.
