### ISSUE TITLE
Html5lib won't install on Python 2.7

### ISSUE THREAD

**Issue by madelinezec** [html5lib/html5lib-python#335]
My python code runs on Python 2.7, but html5lib will only install on 3.5. When I run `pip install html5lib`, I get this nasty message:
<img width="1067" alt="screen shot 2017-04-27 at 10 26 59 am" src="https://cloud.githubusercontent.com/assets/15312869/25488610/7386ab2a-2b35-11e7-8248-222c5bc2f402.png">
I think because of this issue of python versions, when I try to run my python code, I get the exception: 
```
Traceback (most recent call last):
  File "scrapeRecipe.py", line 29, in <module>
    br.select_form(name="aspnetForm")
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_mechanize.py", line 619, in select_form
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_html.py", line 260, in global_form
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_html.py", line 267, in forms
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_html.py", line 282, in _get_forms
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_html.py", line 247, in root
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_html.py", line 145, in content_parser
ImportError: No module named html5lib 
```

What can I do to install html5lib in 2.7?

**Comment by madelinezec** [comment]
I'm getting a different issue now, but this is the solution to the html5lib.
```
pip install --ignore-installed six --user
sudo -H pip install html5lib --ignore-installed
```
To learn more, this is an excellent thread:https://github.com/pypa/pip/issues/3165

**Comment by mumtaztm** [comment]
just write the following command on Anaconda prompt
conda install --force html5lib


its the simple solution
