### ISSUE TITLE
etree serializer fails when serializing lxml.html element containing a comment

### ISSUE THREAD

**Issue by cjerdonek** [html5lib/html5lib-python#340]
Calling `html5lib.serialize()` fails when passing `tree='etree'` and an element containing comments created by `lxml.html`.

This _should_ work because `lxml.html`'s documentation [says](http://lxml.de/lxmlhtml.html) about itself:

> The main API is based on the lxml.etree API, and thus, on the ElementTree API.

Passing `tree='lxml'` doesn't work as a work-around in general because of this issue: https://github.com/html5lib/html5lib-python/issues/338

To reproduce:

    html = """<!DOCTYPE html>
    <html>
    <body>
    
    </body>
    </html>
    """
    element = lxml.html.document_fromstring(html)
    # Works.
    print(html5lib.serialize(element, tree='lxml'))
    # Fails with the exception below.
    print(html5lib.serialize(element, tree='etree'))

Here is the exception:

    Traceback (most recent call last):
      File "test-html5lib.py", line 46, in <module>
        print(html5lib.serialize(element, tree='etree'))
      File "/.../python3.6/site-packages/html5lib/serializer.py", line 78, in serialize
        return s.render(walker(input), encoding)
      File "/.../python3.6/site-packages/html5lib/serializer.py", line 323, in render
        return "".join(list(self.serialize(treewalker)))
      File "/.../python3.6/site-packages/html5lib/serializer.py", line 209, in serialize
        for token in treewalker:
      File "/.../python3.6/site-packages/html5lib/filters/optionaltags.py", line 18, in __iter__
        for previous, token, next in self.slider():
      File "/.../python3.6/site-packages/html5lib/filters/optionaltags.py", line 9, in slider
        for token in self.source:
      File "/.../python3.6/site-packages/html5lib/treewalkers/base.py", line 94, in __iter__
        details = self.getNodeDetails(currentNode)
      File "/.../python3.6/site-packages/html5lib/treewalkers/etree.py", line 61, in getNodeDetails
        assert isinstance(node.tag, string_types), type(node.tag)
    AssertionError: <class 'cython_function_or_method'>

I'm guessing this issue is caused by the type-checking being done in [this line](https://github.com/html5lib/html5lib-python/blob/984f934d30ba2fde0e9ce5d4581c73fb81654474/html5lib/treewalkers/etree.py#L57):

    elif node.tag == ElementTreeCommentType:
        return base.COMMENT, node.text

Instead of exact type-checking which is more fragile, I wonder if some form of duck-typing can be used or using something in the ElementTree API itself.

**Comment by cjerdonek** [comment]
Okay, it looks like it might work to pass `lxml.etree` for the `implementation` argument. I'm not sure if this is supported though (it's not listed as an example value for the argument in the documentation):

    from html5lib.serializer import HTMLSerializer

    def render(element, implementation=None):
        walker_cls = html5lib.getTreeWalker('etree', implementation=implementation)
        walker = walker_cls(element)
        serializer = HTMLSerializer()
        print(serializer.render(walker))

    try:
        render(element)
    except Exception as err:
        print('err: {}'.format(err))

    render(element, implementation=lxml.etree)

Outputs:

    err: <class 'cython_function_or_method'>
    <html>
    <body>
    
    </body>

**Comment by cjerdonek** [comment]
Closing as the ElementTree API doesn't seem to expose a way to detect comments (other than checking the type directly). The documentation could perhaps be improved to list `lxml.etree` as a (third) example value in its documentation of the implementation argument.
