### ISSUE TITLE
etree serializer breaks if an etree.Entity is present

### ISSUE THREAD

**Issue by cjerdonek** [html5lib/html5lib-python#341]
The etree serializer breaks if an Entity object is present.

To reproduce:

    import html5lib
    from html5lib.serializer import HTMLSerializer
    import lxml
    from lxml import etree

    def render(element, treeType, implementation=None):
        walker_cls = html5lib.getTreeWalker(treeType, implementation=implementation)
        walker = walker_cls(element)
        serializer = HTMLSerializer()
        print(serializer.render(walker))

    elements = html5lib.parseFragment('<div></div>', treebuilder='lxml')
    element, = elements
    element.append(etree.Entity('amp'))

    # Works, outputs:
    # <div>&amp;</div>
    render(element, 'lxml')
    # Fails with the exception below.
    render(element, 'etree', implementation=lxml.etree)

Exception:

    Traceback (most recent call last):
      File "test-html5lib.py", line 25, in <module>
        render(element, 'etree', implementation=lxml.etree)
      File "test-html5lib.py", line 16, in render
        print(serializer.render(walker))
      File "/.../python3.6/site-packages/html5lib/serializer.py", line 323, in render
        return "".join(list(self.serialize(treewalker)))
      File "/.../python3.6/site-packages/html5lib/serializer.py", line 209, in serialize
        for token in treewalker:
      File "/.../python3.6/site-packages/html5lib/filters/optionaltags.py", line 18, in __iter__
        for previous, token, next in self.slider():
      File "/.../python3.6/site-packages/html5lib/filters/optionaltags.py", line 9, in slider
        for token in self.source:
      File "/.../python3.6/site-packages/html5lib/treewalkers/base.py", line 94, in __iter__
        details = self.getNodeDetails(currentNode)
      File "/.../python3.6/site-packages/html5lib/treewalkers/etree.py", line 61, in getNodeDetails
        assert isinstance(node.tag, string_types), type(node.tag)
    AssertionError: <class 'cython_function_or_method'>

I believe this is because etree.py's `TreeWalker` class's [`getNodeDetails()` method](https://github.com/html5lib/html5lib-python/blob/984f934d30ba2fde0e9ce5d4581c73fb81654474/html5lib/treewalkers/etree.py#L39) does not have logic like the [following in `etree_lxml.py`](https://github.com/html5lib/html5lib-python/blob/984f934d30ba2fde0e9ce5d4581c73fb81654474/html5lib/treewalkers/etree_lxml.py#L155):

    elif node.tag == etree.Entity:
        return base.ENTITY, ensure_str(node.text)[1:-1]  # strip &;

**Comment by gsnedders** [comment]
As @indivisible mentioned, `etree.Entity` is an `lxml` extension to the ElementTree API.
