### ISSUE TITLE
AttributeError when using html5lib

### ISSUE THREAD

**Issue by tjerkw** [html5lib/html5lib-python#61]
Hi I havea  unit test to ensure my end pages are html5valid.
The test has a function which fails the test if its not valid.

```
def assert_valid_html5(self, html5):
    ''' ensures that the html5 variable consists of valid html5 code '''
    from html5lib import html5parser
    from html5lib import treebuilders
    from html5lib import constants

    treebuilder = treebuilders.getTreeBuilder("etree")
    parser = html5parser.HTMLParser(tree=treebuilder)
    document = parser.parse(html5)

    errors=[]
    for pos, errorcode, datavars in parser.errors:
        errors.append("Line %i Col %i"%pos + " " + constants.E.get(errorcode, 'Unknown error "%s"' % errorcode) % datavars)
    self.assertEquals(len(errors), 0, "expected valid html5, but found errors %s, for html %s" % ("\n".join(errors), html5))
```

The test runs fine on my mac and also fine on the machine of another developer. However on our jenkins node I'm getting an AttributeError.

I'm trying to find what it is, the strange thing is, when i run  "import html5lib" from the python interpreter I don't get any errors. I'm using nosetests to run the tests.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/test_index.py", line 20, in test_index_page
    self.assert_valid_html5(response.body)
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/test_index.py", line 46, in assert_valid_html5
    from html5lib import html5parser
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/rollbackimporter.py", line 13, in _import
    result = apply(self.realImport, (name, globals, locals, fromlist))
  File "/usr/local/lib/python2.7/dist-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/rollbackimporter.py", line 13, in _import
    result = apply(self.realImport, (name, globals, locals, fromlist))
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 6, in <module>
    from . import inputstream
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/rollbackimporter.py", line 13, in _import
    result = apply(self.realImport, (name, globals, locals, fromlist))
  File "/usr/local/lib/python2.7/dist-packages/html5lib/inputstream.py", line 9, in <module>
    from . import utils
  File "/var/lib/jenkins/jobs/bliep-master/workspace/test/rollbackimporter.py", line 13, in _import
    result = apply(self.realImport, (name, globals, locals, fromlist))
  File "/usr/local/lib/python2.7/dist-packages/html5lib/utils.py", line 6, in <module>
    import xml.etree.cElementTree as default_etree
AttributeError: 'module' object has no attribute 'cElementTree'
```

Is this a know issue? I'm trying to figure out whats wrong in the setup but maybe it is also related to html5lib.

**Comment by mdxs** [comment]
When @tjerkw says _"It is nosetests.."_ and "_You can probably close this and see this as a nosetests problem"_ and all this is from 2013; then surely this issue can be closed as-is / wontfix (and when in doubt: see it as a nosetests problem... and still close this issue).
